version: '3'

services:
  apk:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - "3000"
    ports:
    - "3000:3000"
    links:
    - db
    environment:
    - MONGO_URL=mongodb://db/apk
    - ROOT_URL=https://apk.dumfan.net
    - DELAY=30
    - PORT=3000
    - VIRTUAL_HOST=apk.dumfan.net
    - VIRTUAL_PORT=3000
    - LETSENCRYPT_HOST=apk.dumfan.net
    - LETSENCRYPT_EMAIL=benjick@dumfan.net
    restart: always
  db:
    image: mongo
    restart: always
